In [1]:
import pandas as pd

In [2]:
file_loc = "Resources/parties.csv"
parties_df = pd.read_csv(file_loc)
parties_df

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,CASE_ID,PARTY_NUMBER,PARTY_TYPE,AT_FAULT,PARTY_SEX,PARTY_AGE,PARTY_SOBRIETY,PARTY_DRUG_PHYSICAL,DIR_OF_TRAVEL,PARTY_SAFETY_EQUIP_1,...,VEHICLE_YEAR,VEHICLE_MAKE,STWD_VEHICLE_TYPE,CHP_VEH_TYPE_TOWING,CHP_VEH_TYPE_TOWED,RACE,INATTENTION,SPECIAL_INFO_F,SPECIAL_INFO_G,ACCIDENT_YEAR
0,6698657,1,1,Y,F,26,A,-,S,G,...,2014.0,HONDA,A,1.0,NaN,NaN,NaN,-,-,2018
1,6698657,2,4,N,F,52,A,-,N,-,...,NaN,-,L,4.0,NaN,W,NaN,-,-,2018
2,6718742,1,1,N,-,998,G,G,-,-,...,NaN,-,-,NaN,NaN,NaN,NaN,-,-,2018
3,6718742,2,1,Y,-,998,G,G,-,-,...,NaN,-,-,NaN,NaN,NaN,NaN,-,-,2018
4,6718742,3,4,N,M,24,-,-,N,-,...,NaN,-,-,NaN,NaN,W,NaN,-,-,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137573,91235315,3,1,N,M,30,A,-,S,L,...,2012.0,LEXUS,A,1.0,NaN,O,NaN,-,-,2018
137574,91235315,4,1,N,F,36,A,-,S,M,...,2018.0,MERZ,A,1.0,NaN,O,NaN,-,-,2018
137575,91235315,5,1,N,F,54,A,-,S,M,...,2010.0,TOYOTA,A,1.0,NaN,H,NaN,-,-,2018
137576,91235315,6,1,N,M,42,A,-,S,M,...,2017.0,FORD,A,1.0,NaN,W,NaN,-,-,2018
137577,91235315,7,1,N,F,20,A,-,S,M,...,2018.0,MAZDA,A,1.0,NaN,H,NaN,-,-,2018

Inspect data for type and determine if any columns should be removed

In [3]:
parties_df.dtypes

CASE_ID                   int64
PARTY_NUMBER              int64
PARTY_TYPE               object
AT_FAULT                 object
PARTY_SEX                object
PARTY_AGE                 int64
PARTY_SOBRIETY           object
PARTY_DRUG_PHYSICAL      object
DIR_OF_TRAVEL            object
PARTY_SAFETY_EQUIP_1     object
PARTY_SAFETY_EQUIP_2     object
FINAN_RESPONS            object
SP_INFO_1                object
SP_INFO_2                object
SP_INFO_3                object
OAF_VIOLATION_CODE       object
OAF_VIOL_CAT             object
OAF_VIOL_SECTION        float64
OAF_VIOLATION_SUFFIX     object
OAF_1                    object
OAF_2                    object
PARTY_NUMBER_KILLED       int64
PARTY_NUMBER_INJURED      int64
MOVE_PRE_ACC             object
VEHICLE_YEAR            float64
VEHICLE_MAKE             object
STWD_VEHICLE_TYPE        object
CHP_VEH_TYPE_TOWING     float64
CHP_VEH_TYPE_TOWED      float64
RACE                     object
INATTENTION              object
SPECIAL_INFO_F           object
SPECIAL_INFO_G           object
ACCIDENT_YEAR             int64
dtype: object

Replace "-" with "" for each cell in the DataFrame

In [7]:
parties_df.replace("-", "NaN", regex=True)

,CASE_ID,PARTY_NUMBER,PARTY_TYPE,AT_FAULT,PARTY_SEX,PARTY_AGE,PARTY_SOBRIETY,PARTY_DRUG_PHYSICAL,DIR_OF_TRAVEL,PARTY_SAFETY_EQUIP_1,...,VEHICLE_YEAR,VEHICLE_MAKE,STWD_VEHICLE_TYPE,CHP_VEH_TYPE_TOWING,CHP_VEH_TYPE_TOWED,RACE,INATTENTION,SPECIAL_INFO_F,SPECIAL_INFO_G,ACCIDENT_YEAR
0,6698657,1,1,Y,F,26,A,NaN,S,G,...,2014.0,HONDA,A,1.0,NaN,NaN,NaN,NaN,NaN,2018
1,6698657,2,4,N,F,52,A,NaN,N,NaN,...,NaN,NaN,L,4.0,NaN,W,NaN,NaN,NaN,2018
2,6718742,1,1,N,NaN,998,G,G,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
3,6718742,2,1,Y,NaN,998,G,G,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
4,6718742,3,4,N,M,24,NaN,NaN,N,NaN,...,NaN,NaN,NaN,NaN,NaN,W,NaN,NaN,NaN,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137573,91235315,3,1,N,M,30,A,NaN,S,L,...,2012.0,LEXUS,A,1.0,NaN,O,NaN,NaN,NaN,2018
137574,91235315,4,1,N,F,36,A,NaN,S,M,...,2018.0,MERZ,A,1.0,NaN,O,NaN,NaN,NaN,2018
137575,91235315,5,1,N,F,54,A,NaN,S,M,...,2010.0,TOYOTA,A,1.0,NaN,H,NaN,NaN,NaN,2018
137576,91235315,6,1,N,M,42,A,NaN,S,M,...,2017.0,FORD,A,1.0,NaN,W,NaN,NaN,NaN,2018
137577,91235315,7,1,N,F,20,A,NaN,S,M,...,2018.0,MAZDA,A,1.0,NaN,H,NaN,NaN,NaN,2018