In [24]:
import pandas as pd

In [37]:
file_loc = "Resources/parties.csv"
parties_df = pd.read_csv(file_loc)
parties_df

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,CASE_ID,PARTY_NUMBER,PARTY_TYPE,AT_FAULT,PARTY_SEX,PARTY_AGE,PARTY_SOBRIETY,PARTY_DRUG_PHYSICAL,DIR_OF_TRAVEL,PARTY_SAFETY_EQUIP_1,...,VEHICLE_YEAR,VEHICLE_MAKE,STWD_VEHICLE_TYPE,CHP_VEH_TYPE_TOWING,CHP_VEH_TYPE_TOWED,RACE,INATTENTION,SPECIAL_INFO_F,SPECIAL_INFO_G,ACCIDENT_YEAR
0,90655491,1,1,Y,M,26,B,-,S,M,...,2004.0,NISSAN,A,8.0,NaN,H,NaN,-,-,2018
1,90721682,1,1,Y,F,30,A,-,S,L,...,2008.0,HYUN,A,1.0,NaN,B,NaN,-,-,2018
2,90721682,2,1,N,F,41,A,-,S,M,...,2017.0,BMW,A,7.0,NaN,W,NaN,-,-,2018
3,90600484,1,1,Y,M,70,A,-,E,M,...,1998.0,FORD,D,22.0,NaN,B,NaN,-,-,2017
4,90600484,2,3,N,-,998,H,H,W,-,...,2015.0,NISS,A,1.0,NaN,NaN,NaN,-,-,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410211,91151686,2,1,N,M,33,A,-,N,M,...,2017.0,NISS,A,7.0,NaN,O,NaN,-,-,2019
410212,91151686,3,1,N,M,31,A,-,N,M,...,2010.0,TOYT,A,1.0,NaN,O,NaN,-,-,2019
410213,91151686,4,1,N,M,37,A,-,N,M,...,2016.0,ACUR,A,7.0,NaN,O,NaN,-,-,2019
410214,91156085,1,1,Y,M,48,B,-,E,L,...,2003.0,HYUN,A,1.0,NaN,H,NaN,-,-,2019
410215,91156085,2,1,N,M,26,B,-,W,L,...,2018.0,MAZD,A,1.0,NaN,H,NaN,-,-,2019

Inspect data for type and determine if any columns should be removed

In [38]:
parties_df.dtypes

CASE_ID                   int64
PARTY_NUMBER              int64
PARTY_TYPE               object
AT_FAULT                 object
PARTY_SEX                object
PARTY_AGE                 int64
PARTY_SOBRIETY           object
PARTY_DRUG_PHYSICAL      object
DIR_OF_TRAVEL            object
PARTY_SAFETY_EQUIP_1     object
PARTY_SAFETY_EQUIP_2     object
FINAN_RESPONS            object
SP_INFO_1                object
SP_INFO_2                object
SP_INFO_3                object
OAF_VIOLATION_CODE       object
OAF_VIOL_CAT             object
OAF_VIOL_SECTION        float64
OAF_VIOLATION_SUFFIX     object
OAF_1                    object
OAF_2                    object
PARTY_NUMBER_KILLED       int64
PARTY_NUMBER_INJURED      int64
MOVE_PRE_ACC             object
VEHICLE_YEAR            float64
VEHICLE_MAKE             object
STWD_VEHICLE_TYPE        object
CHP_VEH_TYPE_TOWING     float64
CHP_VEH_TYPE_TOWED      float64
RACE                     object
INATTENTION              object
SPECIAL_INFO_F           object
SPECIAL_INFO_G           object
ACCIDENT_YEAR             int64
dtype: object

Replace "-" with "" for each cell in the DataFrame

In [39]:
parties_df.replace("-", "NaN", regex=True)

,CASE_ID,PARTY_NUMBER,PARTY_TYPE,AT_FAULT,PARTY_SEX,PARTY_AGE,PARTY_SOBRIETY,PARTY_DRUG_PHYSICAL,DIR_OF_TRAVEL,PARTY_SAFETY_EQUIP_1,...,VEHICLE_YEAR,VEHICLE_MAKE,STWD_VEHICLE_TYPE,CHP_VEH_TYPE_TOWING,CHP_VEH_TYPE_TOWED,RACE,INATTENTION,SPECIAL_INFO_F,SPECIAL_INFO_G,ACCIDENT_YEAR
0,90655491,1,1,Y,M,26,B,NaN,S,M,...,2004.0,NISSAN,A,8.0,NaN,H,NaN,NaN,NaN,2018
1,90721682,1,1,Y,F,30,A,NaN,S,L,...,2008.0,HYUN,A,1.0,NaN,B,NaN,NaN,NaN,2018
2,90721682,2,1,N,F,41,A,NaN,S,M,...,2017.0,BMW,A,7.0,NaN,W,NaN,NaN,NaN,2018
3,90600484,1,1,Y,M,70,A,NaN,E,M,...,1998.0,FORD,D,22.0,NaN,B,NaN,NaN,NaN,2017
4,90600484,2,3,N,NaN,998,H,H,W,NaN,...,2015.0,NISS,A,1.0,NaN,NaN,NaN,NaN,NaN,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410211,91151686,2,1,N,M,33,A,NaN,N,M,...,2017.0,NISS,A,7.0,NaN,O,NaN,NaN,NaN,2019
410212,91151686,3,1,N,M,31,A,NaN,N,M,...,2010.0,TOYT,A,1.0,NaN,O,NaN,NaN,NaN,2019
410213,91151686,4,1,N,M,37,A,NaN,N,M,...,2016.0,ACUR,A,7.0,NaN,O,NaN,NaN,NaN,2019
410214,91156085,1,1,Y,M,48,B,NaN,E,L,...,2003.0,HYUN,A,1.0,NaN,H,NaN,NaN,NaN,2019
410215,91156085,2,1,N,M,26,B,NaN,W,L,...,2018.0,MAZD,A,1.0,NaN,H,NaN,NaN,NaN,2019

In [34]:
# Determine number of null entries
parties_df.isnull().sum()

CASE_ID                      0
PARTY_NUMBER                 0
PARTY_TYPE                   0
AT_FAULT                     0
PARTY_SEX                    0
PARTY_AGE                    0
PARTY_SOBRIETY               0
PARTY_DRUG_PHYSICAL       2219
DIR_OF_TRAVEL                0
PARTY_SAFETY_EQUIP_1         0
PARTY_SAFETY_EQUIP_2         0
FINAN_RESPONS            23123
SP_INFO_1                    0
SP_INFO_2                    0
SP_INFO_3                    0
OAF_VIOLATION_CODE       22692
OAF_VIOL_CAT                 0
OAF_VIOL_SECTION        387522
OAF_VIOLATION_SUFFIX    402246
OAF_1                        0
OAF_2                        0
PARTY_NUMBER_KILLED          0
PARTY_NUMBER_INJURED         0
MOVE_PRE_ACC                 0
VEHICLE_YEAR             49015
VEHICLE_MAKE                 3
STWD_VEHICLE_TYPE            0
CHP_VEH_TYPE_TOWING      27335
CHP_VEH_TYPE_TOWED      406204
RACE                     51759
INATTENTION             400008
SPECIAL_INFO_F               0
SPECIAL_INFO_G               0
ACCIDENT_YEAR                0
dtype: int64

In [40]:
# Drop columns with large number of null cells
parties_df = parties_df.drop(columns=["OAF_VIOL_SECTION", "OAF_VIOLATION_SUFFIX", "CHP_VEH_TYPE_TOWED", "INATTENTION"])
parties_df

,CASE_ID,PARTY_NUMBER,PARTY_TYPE,AT_FAULT,PARTY_SEX,PARTY_AGE,PARTY_SOBRIETY,PARTY_DRUG_PHYSICAL,DIR_OF_TRAVEL,PARTY_SAFETY_EQUIP_1,...,PARTY_NUMBER_INJURED,MOVE_PRE_ACC,VEHICLE_YEAR,VEHICLE_MAKE,STWD_VEHICLE_TYPE,CHP_VEH_TYPE_TOWING,RACE,SPECIAL_INFO_F,SPECIAL_INFO_G,ACCIDENT_YEAR
0,90655491,1,1,Y,M,26,B,-,S,M,...,1,B,2004.0,NISSAN,A,8.0,H,-,-,2018
1,90721682,1,1,Y,F,30,A,-,S,L,...,0,B,2008.0,HYUN,A,1.0,B,-,-,2018
2,90721682,2,1,N,F,41,A,-,S,M,...,1,B,2017.0,BMW,A,7.0,W,-,-,2018
3,90600484,1,1,Y,M,70,A,-,E,M,...,1,B,1998.0,FORD,D,22.0,B,-,-,2017
4,90600484,2,3,N,-,998,H,H,W,-,...,0,O,2015.0,NISS,A,1.0,NaN,-,-,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410211,91151686,2,1,N,M,33,A,-,N,M,...,1,H,2017.0,NISS,A,7.0,O,-,-,2019
410212,91151686,3,1,N,M,31,A,-,N,M,...,0,A,2010.0,TOYT,A,1.0,O,-,-,2019
410213,91151686,4,1,N,M,37,A,-,N,M,...,0,A,2016.0,ACUR,A,7.0,O,-,-,2019
410214,91156085,1,1,Y,M,48,B,-,E,L,...,3,E,2003.0,HYUN,A,1.0,H,-,-,2019
410215,91156085,2,1,N,M,26,B,-,W,L,...,0,B,2018.0,MAZD,A,1.0,H,-,-,2019

In [41]:
# Drop null values
parties_df = parties_df.dropna()
parties_df

,CASE_ID,PARTY_NUMBER,PARTY_TYPE,AT_FAULT,PARTY_SEX,PARTY_AGE,PARTY_SOBRIETY,PARTY_DRUG_PHYSICAL,DIR_OF_TRAVEL,PARTY_SAFETY_EQUIP_1,...,PARTY_NUMBER_INJURED,MOVE_PRE_ACC,VEHICLE_YEAR,VEHICLE_MAKE,STWD_VEHICLE_TYPE,CHP_VEH_TYPE_TOWING,RACE,SPECIAL_INFO_F,SPECIAL_INFO_G,ACCIDENT_YEAR
1,90721682,1,1,Y,F,30,A,-,S,L,...,0,B,2008.0,HYUN,A,1.0,B,-,-,2018
2,90721682,2,1,N,F,41,A,-,S,M,...,1,B,2017.0,BMW,A,7.0,W,-,-,2018
5,90600867,1,1,N,M,29,C,-,N,M,...,2,B,2012.0,HONDA,A,1.0,B,-,-,2017
6,90600867,2,1,Y,F,53,A,-,N,L,...,1,J,2017.0,BMW,A,1.0,B,-,-,2017
7,90603201,1,1,Y,F,67,A,-,S,M,...,0,B,2014.0,TOYO,A,1.0,W,-,-,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410209,91149181,2,1,N,F,20,A,-,N,M,...,0,B,2019.0,VOLK,A,7.0,O,-,-,2019
410210,91151686,1,1,Y,M,23,A,-,N,M,...,0,B,2008.0,HOND,A,1.0,H,-,-,2019
410211,91151686,2,1,N,M,33,A,-,N,M,...,1,H,2017.0,NISS,A,7.0,O,-,-,2019
410212,91151686,3,1,N,M,31,A,-,N,M,...,0,A,2010.0,TOYT,A,1.0,O,-,-,2019
410213,91151686,4,1,N,M,37,A,-,N,M,...,0,A,2016.0,ACUR,A,7.0,O,-,-,2019

In [42]:
parties_df['ACCIDENT_YEAR'].value_counts()

2017    96104
2018    95458
2019    91238
Name: ACCIDENT_YEAR, dtype: int64